Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 1067, in doRead
    protocol = self.factory.buildProtocol(self._buildAddr(addr))
  File "/usr/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 135, in buildProtocol
    p = self.protocol()
  File "fw_server.py", line 26, in __init__
    self.f.connDev()
  File "/home/mro/ScienceCamera/filter/FilterMotor.py", line 40, in connDev
    self.stepper.waitForAttach(10000)
  File "/usr/local/lib/python2.7/dist-packages/Phidgets/Phidget.py", line 768, in waitForAttach
    raise PhidgetException(result)
Phidgets.PhidgetException.PhidgetException: 

